job_categories:

  - category: "Machine Learning Engineer"
    keywords:
      - "machine learning engineer"
      - "ml engineer"
      - "machine learning developer"
      - "ml developer"

  - category: "Data Scientist"
    keywords:
      - "data scientist"
      - "data science"
      - "applied scientist"
      - "research scientist"

  - category: "Data Analyst"
    keywords:
      - "data analyst"
      - "data analytics"
      - "analytics analyst"

  - category: "Data Engineer"
    keywords:
      - "data engineer"
      - "data engineering"
      - "etl developer"

  - category: "Software Engineer"
    keywords:
      - "software engineer"
      - "software developer"
      - "software development engineer"
      - "sde"

  - category: "Business Analyst"
    keywords:
      - "business analyst"
      - "business analysis"

  - category: "Database"
    keywords:
      - "database administrator"
      - "database developer"
      - "database engineer"

  - category: "Business Intelligence"
    keywords:
      - "bi developer"
      - "business intelligence"
      - "business intelligence developer"
      - "tableau developer"

  - category: "AI Engineer"
    keywords:
      - "ai engineer"
      - "ai developer"
      - "artificial intelligence engineer"

  - category: "Cloud Engineer"
    keywords:
      - "cloud engineer"
      - "cloud developer"
      - "cloud architect"